server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/songs
    username: admin
    password: admin1234
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    queues:
      song-create: SONG_CREATE
      song-created: SONG_CREATED