version: '3.7'
services:
  songs_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=songs
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data: